version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 5000:3000
    volumes:
      - /var/web/frontend/node_modules
      - .:/var/web/frontend
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /var/web/frontend/node_modules
      - .:/var/web/frontend
    command: ["npm", "run", "test"]